server:
  port: 8889
  servlet:
    session:
      timeout: 600000

spring:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/iam?characterEncoding=utf8
    driverClass: com.mysql.jdbc.Driver
    user: root
    password: ldvv
  thymeleaf:
    prefix: classpath:/static/
  security:
    basic:
      enable: false
  session:
    store-type: redis

redis:
  host: 127.0.0.1
  port: 6379
  password: