server:
  port: 8889

spring:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/iam?characterEncoding=utf8
    driverClass: com.mysql.jdbc.Driver
    user: root
    password: ldvv
  thymeleaf:
    prefix: classpath:/static/
  security:
    basic:
      enable: false

redis:
  host: 192.168.220.30
  port: 6379
  password: