server:
  port: 8889
  servlet:
    session:
      timeout: 600000

spring:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/iam?characterEncoding=utf8
    driverClass: com.mysql.jdbc.Driver
    user: root
    password: ldvv
  thymeleaf:
    prefix: classpath:/static/
  security:
    basic:
      enable: false
  session:
    store-type: redis

redis:
  host: 192.168.12.52
  port: 6379
  password: ldvv

#Elasticsearch
elasticsearch:
  name: tomtopccs
  ip: 192.168.0.232
  port: 9300
  pool: 5