server:
  port: 8889

spring:
  datasource:
    jdbcUrl: jdbc:mysql://localhost:3306/iam?characterEncoding=utf8
    driverClass: com.mysql.jdbc.Driver
    user: root
    password: ldvv

mybatis:
  mapper-locations: classpath:com/sys/dao/*.xml
  config-location: classpath:mybatis.xml

