server:
  port: 8888

spring:
  application:
    name: git-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ldvv/ldvv.git
          username: ldvv
          password: ding931205
          search-paths: ldvv
