server:
  port: 8761

spring:
  application:
    name: eureka

eureka:
  instance:
    hostname: localhost
  server:
    service-url: http://${eureka.instance.hostname}:${server.port}/eureka
  client:
    register-with-eureka: false
    fetch-registry: false

