server:
  port: 8761
  ssl:
    enabled: true
    client-auth: want
    key-store: classpath:server.jks
    key-store-password: eureka
    trust-store: classpath:servertrust.jks
    trust-store-password: eureka

spring:
  application:
    name: eureka
  security:
    user:
      name: user
      password: ldvv

eureka:
  instance:
    hostname: localhost
  server:
    service-url: https://${eureka.instance.hostname}:${server.port}/eureka
  client:
    register-with-eureka: false
    fetch-registry: false
